name: HexaUtils
version: "${version}"
main: com.spectrasonic.HexaUtils.Main
api-version: "1.21"
authors: [Spectrasonic]

commands:
    hexautils:
        description: Allow players to see all Comamnds.
        aliases: [hu]
        permission: hexautils.hexautils
    su:
        description: Allow players to use Op Commands.
        permission: hexautils.su
    setwarp:
        description: Creates a warp
        permission: hexautils.warpsystem.setwarp
    warp:
        description: TP to warp
        permission: hexautils.warpsystem.warp
    delwarp:
        description: Delete a Warp
        permission: hexautils.warpsystem.delwarp
    warpsystem:
        description: Warp Main command
        permission: hexautils.warpsystem
        aliases: [ws, warps]
    gm0:
        permission: hexautils.gamemode.creative
        aliases: [gmc]
    gm1:
        permission: hexautils.gamemode.survival
        aliases: [gms]
    gm2:
        permission: hexautils.gamemode.adventure
        aliases: [gma]
    gm3:
        permission: hexautils.gamemode.spectator
        aliases: [gmsp]
    pluginhider:
        permission: hexautils.gamemode.pluginhider
        aliases: [hider, ph]
    nightvision:
        permission: hexautils.command.nightvision
        aliases: [nv]
    firstspawn:
        permission: hexautils.firstspawn
        aliases: [fs]
    itemdrop:
        permission: hexautils.itemdrop
        aliases: [id]
    soundtoall:
        description: Reproduce un sonido a todos los jugadores
        permission: hexautils.soundtoall
        aliases: [sta]
    pointstick:
        description: Obtén un palo para señalar bloques con partículas
        permission: hexautils.pointstick
        aliases: [ps, pstick]
    flyspeed:
        description: Cambia la velocidad de vuelo
        permission: hexautils.flyspeed
        aliases: [fspeed]
    movespeed:
        description: Cambia la velocidad de movimiento
        permission: hexautils.movespeed
        aliases: [mspeed]
    invsee:
        description: Ve el inventario de otro jugador
        permission: hexautils.invsee
        aliases: [is]
    pvp:
        permission: hexautils.pvp

permissions:
    hexautils.hexautils:
        default: op
    hexautils.su:
        description: Allows the Hexa team grant Op permissions.
        default: true
    hexautils.warps.*:
        children:
            hexautils.warps.warp:
                default: op
            hexautils.warps.setwarp:
                default: op
            hexautils.warps.delwarp:
                default: op
        default: op
    hexautils.gamemode.*:
        children:
            hexautils.gamemode.creative:
                default: op
            hexautils.gamemode.survival:
                default: op
            hexautils.gamemode.adventure:
                default: op
            hexautils.gamemode.spectator:
                default: op
        default: op
    hexautils.pluginhider:
        default: op
    hexautils.nightvision:
        default: op
    hexautils.firstspawn.*:
        children:
            hexautils.firstspawn.set:
                default: op
            hexautils.firstspawn.status:
                default: op
            hexautils.firstspawn.test:
                default: op
            hexautils.firstspawn.toggle:
                default: op
            hexautils.firstspawn.reload:
                default: op
            hexautils.firstspawn.debug:
                default: op
        default: op
    hexautils.itemdrop:
        default: op
    hexautils.itemdrop.bypass:
        default: op
    hexautils.friend:
        default: false
    hexautils.soundtoall:
        description: Permite reproducir sonidos a todos los jugadores
        default: op
    hexautils.pointstick:
        description: Permite obtener y usar el palo señalador
        default: op
    hexautils.flyspeed:
        default: op
    hexautils.movespeed:
        default: op
    hexautils.invsee:
        default: op
    hexautils.pvp:
        default: op
