# Configuration for the plugin

allowed-players:
    - Spectrasonic
    - 0mn1spectra
    - MariaSantana_
    - GGARNETS
    - PerroVelazquez
    - JaziIsai
    - TheNazer
    - Goottsy
    - Makira27
    - JarpPlay
    - ImRadiGamer
    - AlexToolS
    - RazorPlay01

Blocked_Commands:
    - "minecraft:plugins"
    - "minecraft:pl"
    - "minecraft:version"
    - "minecraft:ver"
    - "minecraft:help"
    - "minecraft:?"
    - "plugins"
    - "pl"
    - "version"
    - "ver"
    - "?"
    - "help"
    - "tell"
    - "msg"
    - "me"

FirstSpawn:
    enabled: true
    debug: false
    welcome-message: "<white></white>"
    FirstSpawn_location:
        world: world
        x: 0.0
        y: 64.0
        z: 0.0
        direction: SOUTH
